# Generated by Django 3.0.7 on 2020-06-05 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'managed': True},
        ),
    ]
