# Generated by Django 3.0.7 on 2020-06-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tpi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_criticity', models.CharField(blank=True, max_length=6, null=True)),
                ('managementip', models.CharField(blank=True, max_length=255, null=True)),
                ('osfamily_name', models.CharField(blank=True, max_length=255, null=True)),
                ('osfamily_id', models.IntegerField(blank=True, null=True)),
                ('osversion_id', models.IntegerField(blank=True, null=True)),
                ('osversion_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('ram', models.CharField(blank=True, max_length=255, null=True)),
                ('assignedipsinfo', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('projname', models.CharField(blank=True, max_length=255, null=True)),
                ('appinfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tpi',
                'managed': True,
            },
        ),
    ]
